# Generated by Django 5.2.1 on 2025-05-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='api_shop_pr_categor_d9513a_idx'),
        ),
    ]
